"""empty message

Revision ID: 1d54696ed241
Revises: b07722d55aeb
Create Date: 2026-04-19 13:23:50.983052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1d54696ed241'
down_revision: Union[str, Sequence[str], None] = 'b07722d55aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('castell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('posicions', sa.Integer(), nullable=True),
    sa.Column('max_rengles', sa.Integer(), nullable=True),
    sa.Column('max_reserves', sa.Integer(), nullable=True),
    sa.Column('num_castellers', sa.Integer(), nullable=True),
    sa.Column('equacions', sa.Integer(), nullable=True),
    sa.Column('tipus_tronc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_iters', sa.Integer(), nullable=True),
    sa.Column('min_iters', sa.Integer(), nullable=True),
    sa.Column('rengles_pes', sa.Integer(), nullable=True),
    sa.Column('x_folre', sa.Integer(), nullable=True),
    sa.Column('x_manilles', sa.Integer(), nullable=True),
    sa.Column('x_pinya', sa.Integer(), nullable=True),
    sa.Column('x_tronc', sa.Integer(), nullable=True),
    sa.Column('y_folre', sa.Integer(), nullable=True),
    sa.Column('y_manilles', sa.Integer(), nullable=True),
    sa.Column('y_pinya', sa.Integer(), nullable=True),
    sa.Column('y_tronc', sa.Integer(), nullable=True),
    sa.Column('dist_cordo', sa.Integer(), nullable=True),
    sa.Column('angle_inioffset', sa.Integer(), nullable=True),
    sa.Column('long_tit', sa.Float(), nullable=True),
    sa.Column('rang_mapa_r1', sa.Integer(), nullable=True),
    sa.Column('offset_mapa_r1', sa.Integer(), nullable=True),
    sa.Column('offset_titol_r1', sa.Integer(), nullable=True),
    sa.Column('rang_mapa_r2', sa.Integer(), nullable=True),
    sa.Column('offset_mapa_r2', sa.Integer(), nullable=True),
    sa.Column('offset_titol_r2', sa.Integer(), nullable=True),
    sa.Column('rang_mapa_r3', sa.Integer(), nullable=True),
    sa.Column('offset_mapa_r3', sa.Integer(), nullable=True),
    sa.Column('offset_titol_r3', sa.Integer(), nullable=True),
    sa.Column('grafic_vmax', sa.Integer(), nullable=True),
    sa.Column('grafic_nivvert', sa.Integer(), nullable=True),
    sa.Column('grafic_nivhor', sa.Integer(), nullable=True),
    sa.Column('cordo_cm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('castell')
    # ### end Alembic commands ###
