"""empty message

Revision ID: 8cd44f996105
Revises: 1d54696ed241
Create Date: 2026-04-19 13:58:48.937103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8cd44f996105'
down_revision: Union[str, Sequence[str], None] = '1d54696ed241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('castell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pisos', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('castell', schema=None) as batch_op:
        batch_op.drop_column('pisos')

    # ### end Alembic commands ###
